QP-5465 QD-1962 Fix parsing window functions (LAG, LEAD, NTILE)
chequer-io/qsi pull request #67
Opened 2023-11-08 07:13 UTC by zero1ne

### What is this PR? 🔍
[MySQL 8.0.22 버전부터 LEAD, LAG, NTILE 함수의 인자로 다음과 같은 인자를 받을 수 있도록 변경](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-22.html#mysqld-8-0-22-optimizer)되었습니다. 

> Beginning with MySQL 8.0.22, N cannot be NULL. In addition, it must now be an integer in the range 0 to 2^63, inclusive, in any of the following forms:
> 
> an unsigned integer constant literal
> 
> a positional parameter marker(?)
> 
> a user-defined variable
> 
> a local variable in a stored routine

```
LAG(expr [, N[, default]]) [null_treatment] over_clause

LEAD(expr [, N[, default]]) [null_treatment] over_clause

NTILE(N) over_clause
```

따라서 [MySqlParserInternal.g4](https://github.com/chequer-io/qsi/blob/main/Qsi.MySql/Antlr/MySqlParserInternal.g4)의 [leadLagInfo](https://github.com/chequer-io/qsi/blob/main/Qsi.MySql/Antlr/MySqlParserInternal.g4#L2543)에서도 인자의 범위를 확대하였습니다.

### Issue 📌
- [https://chequer.atlassian.net/browse/QCP-1303](https://chequer.atlassian.net/browse/QCP-1303)
- [https://chequer.atlassian.net/browse/QP-5465](https://chequer.atlassian.net/browse/QP-5465)

2023-11-08 07:25 UTC, Web-Engine approved these changes

2023-11-10 08:26 UTC, greg-im approved these changes

2023-11-13 05:19 UTC, evan-choi requested changes

2023-11-13 05:19 UTC, evan-choi commented on Qsi.Tests/Vendor/MySql/MySqlTest.cs
> +            (() => Engine.Execute(new QsiScript(sql, QsiScriptType.Select), null).AsTask()); }
Rider에서 Reformat Code 로 코드 정리 한번 하면 좋을것 같아요

2023-11-13 05:19 UTC, evan-choi commented on Qsi.MySql/Tree/Visitors/ExpressionVisitor.cs
기존 LEAD,LAG 구현에서 첫번째 expr만 탐색하고 있어서
두번째 인자부터는 분석이 무시되고 있어요.

```SQL
SELECT LEAD(first_name, last_name) OVER(ORDER BY actor_id) FROM actor
```

2023-11-13 07:09 UTC, zero1ne commented on Qsi.MySql/Tree/Visitors/ExpressionVisitor.cs
@evan-choi 확인 감사합니다!🥲 
3번째 optional 인자인 default value도 탐색할 수 있도록 VisitLeadLagInfo 함수를 별도로 만들었습니다.

2023-11-13 08:49 UTC, evan-choi approved these changes

2023-11-13 08:51 UTC, merged