[QP-6168] Fix merge statement
chequer-io/qsi pull request #69
Opened 2024-01-17 05:25 UTC by tony-jang

## What is this PR? 🔍

Merge 구문에서 생성되는 ValueTable 대상이 잘못 만들어지던 문제와 다른 문제를 같이 해결합니다.

## Changes 📝
- `(table_name) alias` 구문을 허용합니다. (기존에는 오류가 발생)
- `MERGE ~ INSERT` 구문에서 생성되는 ValueTable에서 alias 처리가 잘못되어 잘못된 쿼리를 생성하던 것을 수정합니다.
- `MERGE` 구문의 기본 Parse 함수를 테스트 할 수 있도록 가장 기본적인 테스트코드를 추가합니다.
- Oracle ANTLR의 `root` Rule에서 `sqlplusCommand`를 제외합니다. (잘못 인식되는 경우 방지)
- Oracle ANTLR의 `revoke` Rule이 잘못되어 있던 문제를 해결합니다.

## Issue 📌

https://chequer.atlassian.net/browse/QP-6168

2024-01-18 08:09 UTC, evan-choi requested changes

2024-01-18 08:09 UTC, evan-choi commented on Qsi.Oracle/Tree/Visitors/ActionVisitor.cs
> +                    _ => throw new InvalidOperationException("Delete target must be Aliased or Reference table")
QSI 에러 코드를 사용하는 코드로 변경해주세요.
마땅한 에러코드가 없다면 새로 정의해도 됩니다.

2024-01-18 08:10 UTC, evan-choi commented on Qsi.Oracle/Antlr/OracleParserInternal.g4
> +    : (fullObjectPath | '(' fullObjectPath ')') ( partitionExtensionClause
이렇게도 되나요?
```sql
(((a.b.c))) AS d
```

2024-01-18 08:42 UTC, tony-jang commented on Qsi.Oracle/Antlr/OracleParserInternal.g4
> +    : (fullObjectPath | '(' fullObjectPath ')') ( partitionExtensionClause
실제 Oracle에서 가능한 스펙으로 확인되어 수정 및 테스트 코드 작성하여 커밋했습니다.

감사합니다.

2024-01-18 08:46 UTC, tony-jang commented on Qsi.Oracle/Tree/Visitors/ActionVisitor.cs
> +                    _ => throw new InvalidOperationException("Delete target must be Aliased or Reference table")
코드를 다시 확인해본 결과 leftSource는 Reference Table에 Alias만 추가되기에 의미 없는 분기 및 오류라고 판단하여 원본 Reference Table인 leftNode를 사용하도록 수정했습니다.

2024-01-29 08:12 UTC, challenger71498 approved these changes

2024-01-31 07:41 UTC, merged