[QP-7661] PostgreSQL에서 ResolveColumnTargetsFromDataInsertAction 오버라이드
chequer-io/qsi pull request #74
Opened 2024-04-09 04:47 UTC by irwin-chequer

## What is this PR? 🔍

`INSERT INTO [테이블] [SQL 쿼리]` 구문의 경우 PostgreSQL에서는 테이블의 컬럼 수와 쿼리의 컬럼 수가 다르더라도 (테이블의 앞쪽 컬럼부터) 삽입을 받아들이지만, QSI에서는  resolve한 target column의 수가 query의 컬럼 수와 다른 경우 `QSI-000F: The used Statements have a different number of columns.` 에러를 일으킵니다. 

이 PR은 PostgreSQL의 경우 target column을 resolve 하는 메소드를 override해서 target column을 query의 컬럼 개수만큼만 resolve 하도록 해 이 에러를 피합니다.

## Issue 📌

https://chequer.atlassian.net/browse/QP-7661

2024-04-12 03:26 UTC, evan-choi requested changes

2024-04-12 03:26 UTC, evan-choi commented on Qsi.PostgreSql/Analyzers/PgActionAnalyzer.cs
> +        return ResolveColumnTargetsFromTable(context, table, (PgDerivedTableNode)action.ValueTable);
필요한 값 외 나머지 속성을 검사하는건 IQsiDataInsertActionNode의 변경이 일어났을때
추가된 속성을 검사하지 못함으로 인해 ObjectNullReferenecException 에러가 발생할 수 있습니다.

정확하게 필요한 값만 검사하도록 코드를 수정하는게 어떨까요?

2024-04-12 03:28 UTC, evan-choi requested changes

2024-04-12 03:28 UTC, evan-choi commented on Qsi.PostgreSql/Analyzers/PgActionAnalyzer.cs
> +            .Take(valueTable.Columns.Value.Count)
valueTable.Columns에 작성된 개수와 실제 연산된 컬럼의 개수에 차이가 있을 수 있습니다.
예를 들어 valueTable에 `SELECT * FROM ...` 와 같은 쿼리를 작성한다면 Columns.Value.Count 는 1 이지만
실제 쿼리의 결과는 1개 이상의 컬럼을 가질 수 있습니다.
그렇기 때문에 QsiTableAnalyzer 를 이용하여 ValueTable을 컴파일하고 QsiTableStructure의 Columns 개수를 이용해야합니다.

2024-04-12 09:21 UTC, irwin-chequer commented on Qsi.PostgreSql/Analyzers/PgActionAnalyzer.cs
> +        return ResolveColumnTargetsFromTable(context, table, (PgDerivedTableNode)action.ValueTable);
line 24의 action의 프로퍼티를 검사하는 코드는 base.ResolveColumnTargetsFromDataInsertAction()에서 하는 검사와 동일한 내용이라 해당 코드를 수행하도록 하기 위한 코드인데요.. line 27 의 action.ValueTable을 조회하는 부분에 대한 우려이실까요..?

2024-04-12 09:35 UTC, irwin-chequer commented on Qsi.PostgreSql/Analyzers/PgActionAnalyzer.cs
> +            .Take(valueTable.Columns.Value.Count)
확인 감사합니다..!! 테이블 컴파일이 async 메소드라서 컴파일을 PgActionAnalyzer 안에서 할 수가 없어서 QsiActionAnalyzer에서 컴파일을 하고 action에 담아 전달하는 식으로 커밋 추가해보았습니다. action이 인터페이스로 선언된 변수라 컴파일 결과를 어떻게 전달해야 하나 고민하다 타입캐스트를 했는데 맞는 방향인지 잘 모르겠네요.. 확인 부탁드립니다..!!

2024-04-12 11:56 UTC, evan-choi commented on Qsi.PostgreSql/Analyzers/PgActionAnalyzer.cs
> +        return ResolveColumnTargetsFromTable(context, table, (PgDerivedTableNode)action.ValueTable);
맞습니다.
`base` 에서 검사하는 로직을 부분적으로 재활용 하는것으로 이해가 되는데요,
이 방식은 `IQsiDataInsertActionNode` 인터페이스가 확장될때 마다 `PgActionAnalyzer` 메소드도 수정해야하는 문제가 있습니다.
예를 들어 `IQsiDataInsertActionNode` 인터페이스에 새로운 속성이 추가되면 `base`의 로직은 새 속성을 포함하도록 수정될 수 있고, 이에 따라 `PgActionAnalyzer`에서도 추가적인 조건 검사가 필요할 수 있습니다. 이는 상속 구조에서의 강한 결합도를 나타내며, 유지보수 및 확장성 측면에서 좋지 않습니다.

말이 좀 길었네요. 예시코드입니다.

```C#
// 목적 데이터에 한해 동작을 패치합니다.
if (action.ValueTable is PgDerivedTableNode pgDerivedTableNode)
    return ResolveColumnTargetsFromTable(context, table, pgDerivedTableNode);

// 이외 동작은 추상 클래스 구현에 위임합니다.
return base.ResolveColumnTargetsFromDataInsertAction(context, table, action);
```

2024-04-12 12:27 UTC, evan-choi commented on Qsi.PostgreSql/Analyzers/PgActionAnalyzer.cs
> +            .Take(valueTable.Columns.Value.Count)
Node에 Node를 분석한 결과를 속성으로 가지는것 보다
Node는 AST 관련된 정보만, 분석 결과는 입력과 출력을 가질 수있으면 이상적일것 같네요.

결론은 Qsi 인터페이스 정의 변경 없이 base 클래스의 메소드를 동기 -> 비동기로 패치하는 정도의 수정만 하고
PgActionAnalyzer에서 action.Directives 와 action.ValueTable 을 QsiTableAnalyzer를 통해 분석하는 코드를 작성하는게 어떨지 제안드립니다.

`ResolveColumnTargetsFromDataInsertAction` 메소드를 동기 코드에서 비동기로 변경하는 패치 파일이에요.
[sync_to_async.patch](https://github.com/chequer-io/qsi/files/14958727/sync_to_async.patch)

```diff
diff --git a/Qsi.PrimarSql/Analyzers/PrimarSqlActionAnalyzer.cs b/Qsi.PrimarSql/Analyzers/PrimarSqlActionAnalyzer.cs
index 5a6e255..62facd6 100644
--- a/Qsi.PrimarSql/Analyzers/PrimarSqlActionAnalyzer.cs
+++ b/Qsi.PrimarSql/Analyzers/PrimarSqlActionAnalyzer.cs
@@ -162,7 +162,7 @@ public class PrimarSqlActionAnalyzer : QsiActionAnalyzer
 
         var table = await tableAnalyzer.BuildTableStructure(tableContext, action.Target);
 
-        ColumnTarget[] columnTargets = ResolveColumnTargetsFromDataInsertAction(context, table, action);
+        ColumnTarget[] columnTargets = await ResolveColumnTargetsFromDataInsertActionAsync(context, table, action);
         var insertRows = new QsiDataRowCollection(columnTargets.Length, context.Engine.CacheProviderFactory());
 
         foreach (var value in action.Values)
@@ -197,7 +197,7 @@ public class PrimarSqlActionAnalyzer : QsiActionAnalyzer
         }.ToSingleArray();
     }
 
-    protected override ColumnTarget[] ResolveColumnTargetsFromDataInsertAction(IAnalyzerContext context, QsiTableStructure table, IQsiDataInsertActionNode action)
+    protected override ValueTask<ColumnTarget[]> ResolveColumnTargetsFromDataInsertActionAsync(IAnalyzerContext context, QsiTableStructure table, IQsiDataInsertActionNode action)
     {
         // table.Columns[0] : hash (required)
         // table.Columns[1] : sort (optional)
@@ -271,7 +271,7 @@ public class PrimarSqlActionAnalyzer : QsiActionAnalyzer
             }
         }
 
-        return targets;
+        return ValueTask.FromResult(targets);
     }
 
     private Exception CreateColumnsNotSpecifiedError(IReadOnlyList<QsiTableColumn> notSpecifiedColumns)
diff --git a/Qsi/Analyzers/Action/QsiActionAnalyzer.cs b/Qsi/Analyzers/Action/QsiActionAnalyzer.cs
index a440e60..0085dc4 100644
--- a/Qsi/Analyzers/Action/QsiActionAnalyzer.cs
+++ b/Qsi/Analyzers/Action/QsiActionAnalyzer.cs
@@ -465,7 +465,7 @@ public class QsiActionAnalyzer : QsiAnalyzerBase
             table = (await tableAnalyzer.BuildTableStructure(tableContext, action.Target)).CloneVisibleOnly();
         }
 
-        ColumnTarget[] columnTargets = ResolveColumnTargetsFromDataInsertAction(context, table, action);
+        ColumnTarget[] columnTargets = await ResolveColumnTargetsFromDataInsertActionAsync(context, table, action);
 
         var dataContext = new TableDataInsertContext(context, table)
         {
@@ -506,15 +506,26 @@ public class QsiActionAnalyzer : QsiAnalyzerBase
             .ToArray<IQsiAnalysisResult>();
     }
 
-    protected virtual ColumnTarget[] ResolveColumnTargetsFromDataInsertAction(IAnalyzerContext context, QsiTableStructure table, IQsiDataInsertActionNode action)
+    protected virtual ValueTask<ColumnTarget[]> ResolveColumnTargetsFromDataInsertActionAsync(IAnalyzerContext context, QsiTableStructure table, IQsiDataInsertActionNode action)
     {
-        if (!ListUtility.IsNullOrEmpty(action.Columns))
-            return ResolveColumnTargetsFromIdentifiers(context, table, action.Columns);
+        ColumnTarget[] columnTargets;
 
-        if (!ListUtility.IsNullOrEmpty(action.SetValues))
-            return ResolveSetColumnTargets(context, table, action.SetValues).ToArray<ColumnTarget>();
+        switch (action)
+        {
+            case { Columns.Length: > 0 }:
+                columnTargets = ResolveColumnTargetsFromIdentifiers(context, table, action.Columns);
+                break;
+
+            case { SetValues.Length: > 0 }:
+                columnTargets = ResolveSetColumnTargets(context, table, action.SetValues).ToArray<ColumnTarget>();
+                break;
+
+            default:
+                columnTargets = ResolveColumnTargetsFromTable(context, table);
+                break;
+        }
 
-        return ResolveColumnTargetsFromTable(context, table);
+        return ValueTask.FromResult(columnTargets);
     }
 
     protected virtual ColumnTarget[] ResolveColumnTargetsFromIdentifiers(IAnalyzerContext context, QsiTableStructure table, IEnumerable<QsiQualifiedIdentifier> identifiers)
```

2024-04-15 01:16 UTC, irwin-chequer commented on Qsi.PostgreSql/Analyzers/PgActionAnalyzer.cs
> +        return ResolveColumnTargetsFromTable(context, table, (PgDerivedTableNode)action.ValueTable);
아 결합도가 생기면 base 수정사항마다 override 메소드도 고쳐야 하는 문제가 있다는 말씀이군요..! 수정 완료 했습니다.

2024-04-15 01:19 UTC, irwin-chequer commented on Qsi.PostgreSql/Analyzers/PgActionAnalyzer.cs
> +            .Take(valueTable.Columns.Value.Count)
base 메소드의 타입을 변경한다는 게 왠지 불편했는데 이번에는 그래야 하는 상황이었군요..! 감사합니다 수정 완료 했습니다!

2024-04-15 11:51 UTC, evan-choi approved these changes
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
```

2024-04-15 12:06 UTC, merged