[QP-8003] Insert Action에서 Not Null 제약조건 있는 컬럼에 값 지정 없을 시 에러 처리
chequer-io/qsi pull request #76
Opened 2024-04-12 02:59 UTC by irwin-chequer

1. Insert Action에서 Not Null 제약조건 있는 컬럼이 있음에도 그 컬럼에 Null 값을 대입한다든가, default 값이 없음에도 그 컬럼에는 값을 지정하지 않고 다른 컬럼에만 값을 대입하는 등(예를 들어, `field2`에 Not Null 제약조건 있는데도 `INSERT INTO table1 (field1) VALUES ('1')` 이런 쿼리를 입력하는데 `field2`는 default가 없는 경우 등) 상황이 발생하면 일반적인 RDBMS는 그에 관한 에러 메시지를 출력하며, QSI도 본 프로젝트의 취지상 이 상황에서 에러 메시지를 출력해야 합니다. 하지만 현재 QSI의 코드는 관련 처리가 없습니다.

2. 이 PR은 다음 변경사항을 통해 Not Null 제약조건에 관한 에러를 처리합니다.

    - `QsiTableColumn` 에 `IsNullable` 속성을 추가하고, 이 속성의 default를 `true`로 설정합니다. 에러를 일으키는 조건식은 `IsNullable`이 `false`인 상황을 전제하므로, QSI를 사용하는 프로젝트에서 `IsNullable` 속성에 값을 대입하는 코드 구현을 하지 않는다면 관련 에러가 일어나지 않습니다.

    - Insert Action 수행 전에 테이블에서 값을 대입할 대상 컬럼들을 가져온 후, `CheckNotNullConstraintsExceptTarget` 메소드를 통해 테이블에서 대상 컬럼이 아닌 컬럼이 'Not Null 제약조건을 갖고 있으면서 default 값이 적절히 지정됐는지'를 검사합니다. 대상 컬럼이 아닌 컬럼 중 default 값이 지정된 바 없는데 Not Null 제약조건이 있다면 에러를 일으키도록 합니다.

    - Insert Action 수행 시, 대상 컬럼에 Null 값을 대입해야 하는 상황에서 해당 컬럼에 Not Null 제약조건이 있는 경우에 에러를 일으키도록 합니다.

3. 이 PR의 변경사항을 활용하는 사례로서, PostgreSQL 관련 사용례 테스트 코드를 추가합니다. (즉, Insert Action에서 타겟 테이블의 컬럼에 Not Null 제약조건 있으나 Null을 입력하는 경우에 에러를 일으키도록 하려면 이 프로젝트를 사용할 때 각 테이블의 컬럼이 Not Null 제약조건이 있는지 및 default 값이 있는지 여부를 조회해야 합니다.)

2024-04-12 03:04 UTC, tony-jang requested changes

2024-04-12 03:04 UTC, tony-jang commented on Qsi/Analyzers/Action/QsiActionAnalyzer.cs
> +
사용자 사용성을 고려했을때 어떤 컬럼에서 Not Null 제약 조건 위반이 발생했는지를 알려주는 것이 더 좋을 것 같습니다.

실제 사용성 측면에서 한번 검토해봐주시면 감사하겠습니다.

2024-04-12 05:59 UTC, irwin-chequer commented on Qsi/Analyzers/Action/QsiActionAnalyzer.cs
> +
에러 메시지 수정하고 요 메소드도 새로 구현했습니다!!

2024-04-15 01:28 UTC, zero1ne approved these changes
LGTM:)

2024-04-16 02:20 UTC, merged