[QP-6629] Insert 및 Update의 row에 존재하는 subquery에 대한 컬럼 및 테이블 정보 취득
chequer-io/qsi pull request #84
Opened 2024-05-21 05:27 UTC by challenger71498

WIP

2024-06-03 06:48 UTC, tony-jang requested changes
비교적 간단한 내용들을 코멘트 달았습니다.

확인해보시고 별 문제 없으면 다시 말씀 주시면 Approve 하겠습니다~

2024-06-03 06:48 UTC, tony-jang commented on Qsi/Analyzers/Action/QsiActionAnalyzer.cs
> +            }
ColumnValues가 두번 이상 사용되었기 때문에 변수로 빼서 가독성을 향상 시키는 것이 어떨까요?

Before
``` csharp
for (int i = 0; i < values.Length; i++)
{
    values[i] = ResolveColumnValue(context, action.Value.ColumnValues[i]);
    tablesInRows[i].AddRange(GetTables(action.Value.ColumnValues[i]));
}
```

After
``` csharp
for (int i = 0; i < values.Length; i++)
{
    var columnValue = action.Value.ColumnValues[i];

    values[i] = ResolveColumnValue(context, columnValue);
    tablesInRows[i].AddRange(GetTables(columnValue));
}
```

2024-06-03 06:48 UTC, tony-jang commented on Qsi/Analyzers/Action/QsiActionAnalyzer.cs
> +
`List<T>`는 일반적으로 컬렉션의 변경이 잦은 상황에서 사용하는 것으로 알고 있습니다.

사용처들을 보면 변경이 잦은거 같지는 않아서 `QsiTableStructure[][]` 로 변경해도 괜찮을 것 같은데 혹시 `List<QsiTableStructure>` 를 사용해야만 하셨던 이유가 있을까요?

2024-06-03 10:03 UTC, challenger71498 commented on Qsi/Analyzers/Action/QsiActionAnalyzer.cs
> +
![image](https://github.com/chequer-io/qsi/assets/43464986/9a58f567-8d6d-4309-b436-fe589e80c04a)

확인해보니까 컬럼당 무조건 한번씩만 돌긴 하겠네요 ㅋㅋ

추가적으로 왜 서포트하지 않았는지도 한번 보는것이..

2024-06-04 04:17 UTC, challenger71498 commented on Qsi/Analyzers/Action/QsiActionAnalyzer.cs
> +
List<T>를 IEnumerable<T>을 사용하도록 수정했습니다.

2024-06-04 04:17 UTC, challenger71498 commented on Qsi/Analyzers/Action/QsiActionAnalyzer.cs
> +            }
요거는 3번 반복되면 만드는걸루 할게요 ㅋㅋ

2024-06-04 04:18 UTC, challenger71498 commented
@tony-jang 업데이트했습니다. 다시 확인 부탁드려요~

2024-06-04 04:23 UTC, tony-jang approved these changes
LGTM

2024-06-04 04:23 UTC, merged